name: bio_env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python>=3.12.4
  - ipykernel>=6.29.4
  - bowtie2>=2.5.4
  - bamtools>=2.5.2
  - samtools>=1.20
  - fastqc>=0.12.1
  - salmon>=1.10.3
  - minced>=0.4.2
  - piler-cr>=1.06
  - bzip2>=1.0.8


# After installation create ./envs/bio_env/.condarc configuration file with the following commands:
# ```sh
# conda config --env --add channels defaults
# conda config --env --add channels bioconda
# conda config --env --add channels conda-forge
# conda config --env --set channel_priority strict
# ```

# Package versions at the time of writing this file

# python                         3.12.4
  # - bzip2 >=1.0.8,<2.0a0
  # - expat >=2.6.2,<3.0a0
  # - libffi >=3.4,<4.0a0
  # - ncurses >=6.4,<7.0a0
  # - openssl >=3.0.13,<4.0a0
  # - readline >=8.1.2,<9.0a0
  # - sqlite >=3.45.3,<4.0a0
  # - tk >=8.6.14,<8.7.0a0
  # - tzdata
  # - xz >=5.4.6,<6.0a0
  # - zlib >=1.2.13,<1.3.0a0
  # - pip
# ipykernel                      6.29.4
  # - __osx
  # - appnope
  # - comm >=0.1.1
  # - debugpy >=1.6.5
  # - ipython >=7.23.1
  # - jupyter_client >=6.1.12
  # - jupyter_core >=4.12,!=5.0.*
  # - matplotlib-inline >=0.1
  # - nest-asyncio
  # - packaging
  # - psutil
  # - python >=3.8
  # - pyzmq >=24
  # - tornado >=6.1
  # - traitlets >=5.4.0
# bowtie2                         2.5.4
  # - libcxx >=14
  # - libzlib >=1.2.13,<2.0a0
  # - llvm-openmp >=15.0.7
  # - perl
  # - python
  # - tbb >=2021.12.0
  # - zstd >=1.5.6,<1.6.0a0
# bamtools                       2.5.2
  # - libcxx >=14
  # - libzlib >=1.2.13,<1.3.0a0
# samtools                       1.20
  # - htslib >=1.20,<1.21.0a0
  # - libzlib >=1.2.13,<1.3.0a0
  # - ncurses >=6.4.20240210,<7.0a0
# fastqc                         0.12.1
  # - font-ttf-dejavu-sans-mono
  # - fontconfig
  # - openjdk >=8.0.144
  # - perl
# salmon                         1.10.3
  # - boost-cpp >=1.78.0,<1.78.1.0a0
  # - bzip2 >=1.0.8,<2.0a0
  # - icu >=70.1,<71.0a0
  # - libcxx >=14
  # - libjemalloc >=5.3.0
  # - libzlib >=1.2.13,<1.3.0a0
  # - tbb >=2021.10.0
  # - tbb >=2021.4.0

# bzip2                          1.0.8
# minced                         0.4.2
  # - openjdk >=8
# piler-cr                       1.06
  # - libcxx >=12.0.1